
CREATE DATABASE IF NOT EXISTS taskmanager;
USE taskmanager;

CREATE TABLE IF NOT EXISTS users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100), email VARCHAR(150) UNIQUE, password VARCHAR(255),
 createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks(
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(200), description TEXT, dueDate DATETIME,
 priority ENUM('alta','media','baja') DEFAULT 'media',
 status ENUM('pendiente','en_progreso','completada') DEFAULT 'pendiente',
 userId INT,
 createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE
);
